/**
 * Events Schema Package
 *
 * Provides TypeBox schema definitions for WebSocket events used in Stick Rumble.
 * These schemas serve as the single source of truth for message validation across
 * the TypeScript client and Go server.
 *
 * Usage:
 * ```typescript
 * import { PositionSchema, VelocitySchema, MessageSchema } from '@stick-rumble/events-schema';
 * import type { Position, Velocity, Message } from '@stick-rumble/events-schema';
 * ```
 */

// Export common schemas and types
export {
  PositionSchema,
  VelocitySchema,
  MessageSchema,
  createTypedMessageSchema,
  createTypedMessageSchemaNoData,
  type Position,
  type Velocity,
  type Message,
} from './schemas/common.js';

// Export client-to-server schemas and types
export {
  InputStateDataSchema,
  InputStateMessageSchema,
  PlayerShootDataSchema,
  PlayerShootMessageSchema,
  PlayerReloadMessageSchema,
  WeaponPickupAttemptDataSchema,
  WeaponPickupAttemptMessageSchema,
  PlayerMeleeAttackDataSchema,
  PlayerMeleeAttackMessageSchema,
  PlayerDodgeRollMessageSchema,
  type InputStateData,
  type InputStateMessage,
  type PlayerShootData,
  type PlayerShootMessage,
  type PlayerReloadMessage,
  type WeaponPickupAttemptData,
  type WeaponPickupAttemptMessage,
  type PlayerMeleeAttackData,
  type PlayerMeleeAttackMessage,
  type PlayerDodgeRollMessage,
} from './schemas/client-to-server.js';

// Export server-to-client schemas and types
export {
  RoomJoinedDataSchema,
  RoomJoinedMessageSchema,
  PlayerLeftDataSchema,
  PlayerLeftMessageSchema,
  PlayerStateSchema,
  PlayerMoveDataSchema,
  PlayerMoveMessageSchema,
  ProjectileSpawnDataSchema,
  ProjectileSpawnMessageSchema,
  ProjectileDestroyDataSchema,
  ProjectileDestroyMessageSchema,
  WeaponStateDataSchema,
  WeaponStateMessageSchema,
  ShootFailedDataSchema,
  ShootFailedMessageSchema,
  PlayerDamagedDataSchema,
  PlayerDamagedMessageSchema,
  HitConfirmedDataSchema,
  HitConfirmedMessageSchema,
  PlayerDeathDataSchema,
  PlayerDeathMessageSchema,
  PlayerKillCreditDataSchema,
  PlayerKillCreditMessageSchema,
  PlayerRespawnDataSchema,
  PlayerRespawnMessageSchema,
  MatchTimerDataSchema,
  MatchTimerMessageSchema,
  PlayerScoreSchema,
  MatchEndedDataSchema,
  MatchEndedMessageSchema,
  WeaponCrateSchema,
  WeaponSpawnedDataSchema,
  WeaponSpawnedMessageSchema,
  WeaponPickupConfirmedDataSchema,
  WeaponPickupConfirmedMessageSchema,
  WeaponRespawnedDataSchema,
  WeaponRespawnedMessageSchema,
  MeleeHitDataSchema,
  MeleeHitMessageSchema,
  RollStartDataSchema,
  RollStartMessageSchema,
  RollEndDataSchema,
  RollEndMessageSchema,
  type RoomJoinedData,
  type RoomJoinedMessage,
  type PlayerLeftData,
  type PlayerLeftMessage,
  type PlayerState,
  type PlayerMoveData,
  type PlayerMoveMessage,
  type ProjectileSpawnData,
  type ProjectileSpawnMessage,
  type ProjectileDestroyData,
  type ProjectileDestroyMessage,
  type WeaponStateData,
  type WeaponStateMessage,
  type ShootFailedData,
  type ShootFailedMessage,
  type PlayerDamagedData,
  type PlayerDamagedMessage,
  type HitConfirmedData,
  type HitConfirmedMessage,
  type PlayerDeathData,
  type PlayerDeathMessage,
  type PlayerKillCreditData,
  type PlayerKillCreditMessage,
  type PlayerRespawnData,
  type PlayerRespawnMessage,
  type MatchTimerData,
  type MatchTimerMessage,
  type PlayerScore,
  type MatchEndedData,
  type MatchEndedMessage,
  type WeaponCrate,
  type WeaponSpawnedData,
  type WeaponSpawnedMessage,
  type WeaponPickupConfirmedData,
  type WeaponPickupConfirmedMessage,
  type WeaponRespawnedData,
  type WeaponRespawnedMessage,
  type MeleeHitData,
  type MeleeHitMessage,
  type RollStartData,
  type RollStartMessage,
  type RollEndData,
  type RollEndMessage,
} from './schemas/server-to-client.js';
